CC=g++
CFLAGS=-std=c++11 -Wall -Wextra -pedantic -lp4dev
BINNAME=example

all: $(BINNAME)

Table.o: Table.cpp
	$(CC) $(CFLAGS) $^ -c

Register.o: Register.cpp
	$(CC) $(CFLAGS) $^ -c

RegisterArray.o: RegisterArray.cpp
	$(CC) $(CFLAGS) $^ -c

Device.o: Device.cpp
	$(CC) $(CFLAGS) $^ -c

$(BINNAME): Table.o Register.o RegisterArray.o Device.o
	$(CC) $(CFLAGS) $^ -o $@
